import { extendVars } from 'zyzz'
import { palette } from './palette'

// Tempo's reviewed design vocabulary. Add reusable decisions here; document
// component-specific geometry with !custom at the declaration.
export const design = extendVars(palette, {
  spacing: {
    '0': '0px',
    '1': '4px',
    controlInset: 'calc(var(--spacing) * 3.25)',
    '2': '8px',
    '3': '12px',
    '4': '16px',
    '5': '20px',
    '6': '24px',
    '7': '28px',
    '8': '32px',
    '9': '36px',
    '10': '40px',
    '11': '44px',
    '12': '48px',
    '14': '56px',
    '16': '64px',
    '18': '72px',
    '20': '80px',
    '24': '96px',
    '28': '112px',
    '36': '144px',
    '40': '160px',
    '44': '176px',
    '48': '192px',
    '56': '224px',
    '1_5': '6px',
    '3_5': '14px',
    '2_5': '10px',
    '0_5': '2px',
    // Body section rhythm: 80px (TDS Platform section.md), 64px below 768px.
    section: 'var(--tempo-section-space)',
  },
  fontWeight: {
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
  },
  // Steps from 4px up follow TDS Platform radius (tempoxyz/ds@3fd4cf7):
  // sm = 3xs, md = 2xs, lg = xs, xl = sm, panel = md. Rounded elements also
  // set --corner-radius so SmoothCorners can smooth them (see smoothCorners.ts).
  radius: {
    none: '0px',
    hairline: '1px',
    xs: '2px',
    sm: '4px',
    smRem: '0.25rem',
    full: 'calc(infinity * 1px)',
    pill: '50px',
    round: '50%',
    md: '8px',
    lg: '12px',
    xl: '16px',
    panel: '24px',
  },
  fontSize: {
    micro: '9px',
    tiny: '10px',
    caption: '11px',
    xs: '12px',
    compact: '13px',
    sm: '14px',
    bodySmall: '15px',
    body: '16px',
    lead: '18px',
    subheading: '20px',
    titleSmall: '22px',
    title: '24px',
    heading: '28px',
    displaySmall: '32px',
    display: '40px',
    displayLarge: '48px',
    hero: '64px',
  },
  fontFamily: {
    book: 'var(--font-pilat-book)',
    code: 'var(--font-jetbrains-mono)',
    sansFallback: 'var(--font-pilat-book), sans-serif',
    system: 'var(--font-pilat-book), ui-sans-serif, system-ui, sans-serif',
  },
  letterSpacing: {
    normal: '0',
    // TDS Platform body.b1 tracking.
    b1: '0.12px',
    tight: '-0.01em',
    compact: '-0.02em',
    heading: '-0.03em',
    display: '-0.04em',
    wide: '0.01em',
    wider: '0.02em',
    label: '0.12em',
  },
  lineHeight: {
    caption: '16px',
    control: '20px',
    // TDS Platform body.b1 (16px text).
    b1: '22px',
    dense: '1.35rem',
    body: '1.5rem',
    none: 1,
    display: 1.1,
    heading: 1.2,
    compact: 1.3,
    snug: 1.4,
    normal: 1.5,
    relaxed: 1.6,
    prose: 1.7,
  },
  zIndex: {
    decoration: 'calc(10 * -1)',
    raised: 10,
    overlay: 20,
    floating: 40,
    sectionNav: 50,
    header: 60,
    drawer: 70,
    dialog: 200,
    toast: 9999,
    command: 42069,
  },
  borderWidth: { none: '0px', hairline: '1px', emphasis: '2px' },
})

// Dimensions and positions describe artwork/layout geometry, not rhythm.
// Padding, margins, and gaps must use the spacing scale.
export const mappings = {
  spacing: [
    'gap',
    'rowGap',
    'columnGap',
    'padding',
    'paddingBlock',
    'paddingInline',
    'paddingTop',
    'paddingBottom',
    'paddingLeft',
    'paddingRight',
    'paddingBlockStart',
    'paddingBlockEnd',
    'paddingInlineStart',
    'paddingInlineEnd',
    'margin',
    'marginBlock',
    'marginInline',
    'marginTop',
    'marginBottom',
    'marginLeft',
    'marginRight',
    'marginBlockStart',
    'marginBlockEnd',
    'marginInlineStart',
    'marginInlineEnd',
  ],
  zIndex: ['zIndex'],
} as const
