import { global } from 'zyzz/web'
import { pulse } from './motion'
import { vars } from './theme'

// Compatibility aliases for Vocs and generated prose; values belong to Zyzz.
global({
  ':root': {
    '--font-sans': 'var(--font-pilat-book)',
    '--font-mono': 'var(--font-jetbrains-mono)',
    '--color-red-500': 'oklch(63.7% 0.237 25.331)',
    '--color-gray-600': 'oklch(44.6% 0.03 256.802)',
    '--color-black': vars.color.black,
    '--color-white': vars.color.white,
    '--spacing': '0.25rem',
    '--tempo-section-space': '64px',
    '--container-5xl': '64rem',
    '--container-7xl': '80rem',
    '--text-xs': '0.75rem',
    '--text-xs--line-height': 'calc(1 / 0.75)',
    '--text-sm': '0.875rem',
    '--text-sm--line-height': 'calc(1.25 / 0.875)',
    '--font-weight-normal': '400',
    '--font-weight-medium': '500',
    '--font-weight-semibold': '600',
    '--tracking-tight': '-0.025em',
    '--tracking-wide': '0.025em',
    '--tracking-wider': '0.05em',
    '--leading-tight': '1.25',
    '--leading-snug': '1.375',
    '--leading-normal': '1.5',
    '--leading-relaxed': '1.625',
    '--radius-md': '0.375rem',
    '--radius-lg': '0.5rem',
    '--radius-xl': '0.75rem',
    '--ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
    '--animate-pulse': `${pulse} 2s cubic-bezier(0.4, 0, 0.6, 1) infinite`,
    '--blur-sm': '8px',
    '--default-transition-duration': '150ms',
    '--default-transition-timing-function': 'cubic-bezier(0.4, 0, 0.2, 1)',
    '--font-display': 'var(--font-hbset)',
    '--color-background': 'var(--background)',
    '--color-foreground': 'var(--foreground)',
    '--color-info': 'var(--info)',
    '--color-line': 'var(--line)',
    '--color-on-accent': 'var(--on-accent)',
    '--color-positive': 'var(--positive)',
    '--color-surface-input': 'var(--surface-input)',
    '--color-surface-page': 'var(--surface-page)',
    '--color-gray1': vars.color.gray1,
    '--color-gray2': vars.color.gray2,
    '--color-gray3': vars.color.gray3,
    '--color-gray4': vars.color.gray4,
    '--color-gray5': vars.color.gray5,
    '--color-gray6': vars.color.gray6,
    '--color-gray7': vars.color.gray7,
    '--color-gray8': vars.color.gray8,
    '--color-gray9': vars.color.gray9,
    '--color-gray10': vars.color.gray10,
    '--color-gray11': vars.color.gray11,
    '--color-gray12': vars.color.gray12,
    '--color-grayA1': vars.color.grayA1,
    '--color-grayA2': vars.color.grayA2,
    '--color-grayA3': vars.color.grayA3,
    '--color-grayA4': vars.color.grayA4,
    '--color-grayA5': vars.color.grayA5,
    '--color-grayA6': vars.color.grayA6,
    '--color-grayA7': vars.color.grayA7,
    '--color-grayA8': vars.color.grayA8,
    '--color-grayA9': vars.color.grayA9,
    '--color-grayA10': vars.color.grayA10,
    '--color-grayA11': vars.color.grayA11,
    '--color-grayA12': vars.color.grayA12,
    '--color-blackA1': vars.color.blackA1,
    '--color-blackA2': vars.color.blackA2,
    '--color-blackA3': vars.color.blackA3,
    '--color-blackA4': vars.color.blackA4,
    '--color-blackA5': vars.color.blackA5,
    '--color-blackA6': vars.color.blackA6,
    '--color-blackA7': vars.color.blackA7,
    '--color-blackA8': vars.color.blackA8,
    '--color-blackA9': vars.color.blackA9,
    '--color-blackA10': vars.color.blackA10,
    '--color-blackA11': vars.color.blackA11,
    '--color-blackA12': vars.color.blackA12,
    '--color-whiteA1': vars.color.whiteA1,
    '--color-whiteA2': vars.color.whiteA2,
    '--color-whiteA3': vars.color.whiteA3,
    '--color-whiteA4': vars.color.whiteA4,
    '--color-whiteA5': vars.color.whiteA5,
    '--color-whiteA6': vars.color.whiteA6,
    '--color-whiteA7': vars.color.whiteA7,
    '--color-whiteA8': vars.color.whiteA8,
    '--color-whiteA9': vars.color.whiteA9,
    '--color-whiteA10': vars.color.whiteA10,
    '--color-whiteA11': vars.color.whiteA11,
    '--color-whiteA12': vars.color.whiteA12,
    '--color-blue1': vars.color.blue1,
    '--color-blue2': vars.color.blue2,
    '--color-blue3': vars.color.blue3,
    '--color-blue4': vars.color.blue4,
    '--color-blue5': vars.color.blue5,
    '--color-blue6': vars.color.blue6,
    '--color-blue7': vars.color.blue7,
    '--color-blue8': vars.color.blue8,
    '--color-blue9': vars.color.blue9,
    '--color-blue10': vars.color.blue10,
    '--color-blue11': vars.color.blue11,
    '--color-blue12': vars.color.blue12,
    '--color-blueA1': vars.color.blueA1,
    '--color-blueA2': vars.color.blueA2,
    '--color-blueA3': vars.color.blueA3,
    '--color-blueA4': vars.color.blueA4,
    '--color-blueA5': vars.color.blueA5,
    '--color-blueA6': vars.color.blueA6,
    '--color-blueA7': vars.color.blueA7,
    '--color-blueA8': vars.color.blueA8,
    '--color-blueA9': vars.color.blueA9,
    '--color-blueA10': vars.color.blueA10,
    '--color-blueA11': vars.color.blueA11,
    '--color-blueA12': vars.color.blueA12,
    '--color-amber1': vars.color.amber1,
    '--color-amber2': vars.color.amber2,
    '--color-amber3': vars.color.amber3,
    '--color-amber4': vars.color.amber4,
    '--color-amber5': vars.color.amber5,
    '--color-amber6': vars.color.amber6,
    '--color-amber7': vars.color.amber7,
    '--color-amber8': vars.color.amber8,
    '--color-amber9': vars.color.amber9,
    '--color-amber10': vars.color.amber10,
    '--color-amber11': vars.color.amber11,
    '--color-amber12': vars.color.amber12,
    '--color-amberA1': vars.color.amberA1,
    '--color-amberA2': vars.color.amberA2,
    '--color-amberA3': vars.color.amberA3,
    '--color-amberA4': vars.color.amberA4,
    '--color-amberA5': vars.color.amberA5,
    '--color-amberA6': vars.color.amberA6,
    '--color-amberA7': vars.color.amberA7,
    '--color-amberA8': vars.color.amberA8,
    '--color-amberA9': vars.color.amberA9,
    '--color-amberA10': vars.color.amberA10,
    '--color-amberA11': vars.color.amberA11,
    '--color-amberA12': vars.color.amberA12,
    '--color-green1': vars.color.green1,
    '--color-green2': vars.color.green2,
    '--color-green3': vars.color.green3,
    '--color-green4': vars.color.green4,
    '--color-green5': vars.color.green5,
    '--color-green6': vars.color.green6,
    '--color-green7': vars.color.green7,
    '--color-green8': vars.color.green8,
    '--color-green9': vars.color.green9,
    '--color-green10': vars.color.green10,
    '--color-green11': vars.color.green11,
    '--color-green12': vars.color.green12,
    '--color-red1': vars.color.red1,
    '--color-red2': vars.color.red2,
    '--color-red3': vars.color.red3,
    '--color-red4': vars.color.red4,
    '--color-red5': vars.color.red5,
    '--color-red6': vars.color.red6,
    '--color-red7': vars.color.red7,
    '--color-red8': vars.color.red8,
    '--color-red9': vars.color.red9,
    '--color-red10': vars.color.red10,
    '--color-red11': vars.color.red11,
    '--color-red12': vars.color.red12,
    '--color-violet1': vars.color.violet1,
    '--color-violet2': vars.color.violet2,
    '--color-violet3': vars.color.violet3,
    '--color-violet4': vars.color.violet4,
    '--color-violet5': vars.color.violet5,
    '--color-violet6': vars.color.violet6,
    '--color-violet7': vars.color.violet7,
    '--color-violet8': vars.color.violet8,
    '--color-violet9': vars.color.violet9,
    '--color-violet10': vars.color.violet10,
    '--color-violet11': vars.color.violet11,
    '--color-violet12': vars.color.violet12,
    '--color-jade1': vars.color.jade1,
    '--color-jade2': vars.color.jade2,
    '--color-jade3': vars.color.jade3,
    '--color-jade4': vars.color.jade4,
    '--color-jade5': vars.color.jade5,
    '--color-jade6': vars.color.jade6,
    '--color-jade7': vars.color.jade7,
    '--color-jade8': vars.color.jade8,
    '--color-jade9': vars.color.jade9,
    '--color-jade10': vars.color.jade10,
    '--color-jade11': vars.color.jade11,
    '--color-jade12': vars.color.jade12,
    '--background-color-accent': 'var(--color-blue9)',
    '--background-color-accentHover': 'var(--color-blue10)',
    '--background-color-accentTint': 'var(--color-blueA3)',
    '--background-color-accentTintHover': 'var(--color-blueA4)',
    '--background-color-destructive': 'var(--color-red3)',
    '--background-color-destructiveHover': 'var(--color-red4)',
    '--background-color-destructiveTint': 'var(--color-red3)',
    '--background-color-invert': 'light-dark(var(--color-black), var(--color-white))',
    '--background-color-invertHover': 'light-dark(var(--color-blackA10), var(--color-whiteA10))',
    '--background-color-primary': 'light-dark(var(--color-gray1), var(--color-gray2))',
    '--background-color-primaryHover': 'var(--color-gray3)',
    '--background-color-secondary': 'light-dark(var(--color-gray2), var(--color-gray3))',
    '--background-color-surface': 'var(--color-gray3)',
    '--background-color-surfaceHover': 'var(--color-gray4)',
    '--background-color-success': 'var(--color-green9)',
    '--background-color-successHover': 'var(--color-green10)',
    '--background-color-successTint': 'var(--color-green4)',
    '--background-color-warning': 'var(--color-amber8)',
    '--background-color-warningHover': 'var(--color-amber7)',
    '--background-color-warningTint': 'var(--color-amberA2)',
    '--background-color-violet': 'var(--color-violet9)',
    '--background-color-violetHover': 'var(--color-violet10)',
    '--background-color-violetTint': 'var(--color-violetA3)',
    '--border-color-accent': 'var(--color-blue9)',
    '--border-color-accentHover': 'var(--color-blue10)',
    '--border-color-active': 'light-dark(var(--color-black), var(--color-white))',
    '--border-color-invert': 'light-dark(var(--color-black), var(--color-white))',
    '--border-color-primary': 'light-dark(var(--color-gray5), var(--color-gray4))',
    '--border-color-surface': 'light-dark(var(--color-gray4), var(--color-gray5))',
    '--text-color-accent': 'var(--color-blue10)',
    '--text-color-destructive': 'var(--color-red10)',
    '--text-color-invert': 'light-dark(var(--color-white), var(--color-black))',
    '--text-color-active': 'light-dark(var(--color-black), var(--color-white))',
    '--text-color-primary': 'var(--color-gray12)',
    '--text-color-secondary': 'var(--color-gray10)',
    '--text-color-success': 'var(--color-green10)',
    '--text-color-warning': 'var(--color-amber8)',
    '--height-button': '42px',
    '--spacing-dialog': '360px',
    '--spacing-titlebar': '36px',
    '--radius-default': 'calc(infinity * 1px)',
    '--color-foreground-secondary': 'var(--foreground-secondary)',
    '--color-foreground-secondary-hover': 'var(--foreground-secondary-hover)',
    '--color-negative': 'var(--negative)',
    '--color-warning': 'var(--warning)',
    '--color-on-negative': 'var(--on-negative)',
    '--color-on-surface-onyx': 'var(--on-surface-onyx)',
    '--color-surface-block': 'var(--surface-block)',
    '--color-surface-block-muted': 'var(--surface-block-muted)',
    '--color-surface-card': 'var(--surface-card)',
    '--color-surface-card-elev': 'var(--surface-card-elev)',
    '--color-surface-onyx': 'var(--surface-onyx)',
    '--color-surface-deep': 'var(--surface-deep)',
    '--color-surface-skeleton': 'var(--surface-skeleton)',
    '--color-surface-panel': 'var(--surface-panel)',
    '--color-surface-shell': 'var(--surface-shell)',
    '--color-line-strong': 'var(--line-strong)',
    '--color-line-dashed': 'var(--line-dashed)',
    '--color-accent-blue': 'var(--accent-blue)',
    '--color-indicator-green': 'var(--indicator-green)',
  },
})

global({
  '@media (width >= 768px)': {
    ':root': {
      '--tempo-section-space': '80px',
    },
  },
})

// Defaults must stay below component recipes in the cascade. Unlayered resets
// override even more-specific layered declarations (including drawer transforms).
global({
  '@layer properties': {
    '*, ::before, ::after, ::backdrop': {
      '--tempo-style-space-y-reverse': '0',
      '--tempo-style-border-style': 'solid',
      '--tempo-style-outline-style': 'solid',
      '--tempo-style-translate-x': '0',
      '--tempo-style-translate-y': '0',
      '--tempo-style-translate-z': '0',
      '--tempo-style-shadow': '0 0 #0000',
      '--tempo-style-shadow-alpha': '100%',
      '--tempo-style-inset-shadow': '0 0 #0000',
      '--tempo-style-inset-shadow-alpha': '100%',
      '--tempo-style-ring-shadow': '0 0 #0000',
      '--tempo-style-inset-ring-shadow': '0 0 #0000',
      '--tempo-style-ring-offset-width': '0px',
      '--tempo-style-ring-offset-color': '#fff',
      '--tempo-style-ring-offset-shadow': '0 0 #0000',
      '--tempo-style-gradient-from': '#0000',
      '--tempo-style-gradient-via': '#0000',
      '--tempo-style-gradient-to': '#0000',
      '--tempo-style-gradient-from-position': '0%',
      '--tempo-style-gradient-via-position': '50%',
      '--tempo-style-gradient-to-position': '100%',
      '--tempo-style-scale-x': '1',
      '--tempo-style-scale-y': '1',
      '--tempo-style-scale-z': '1',
    },
  },
})
